precision: 'medium'
dataset: 'split'
bs: 128
patience: 20
save_top_k: 5

image_encoder_args:
  name: 'vit_small_patch16_224'
  pretrained: true
  dropout: 0.1
  metadata: true

optim_args:
  lr: 5.0e-3
  momentum: 0.9
  weight_decay: 1.0e-3
  nesterov: true

trainer_args:
  precision: '16-mixed'
  min_epochs: 40
  max_epochs: 100
  accumulate_grad_batches: 1
  val_check_interval:
  check_val_every_n_epoch: 1
