precision: 'medium'
dim_embedding: 512
max_len: &max_len 256
bs: 64
patience: 20
save_top_k: 5

image_encoder_args:
  name: 'efficientnet_b0'
  pretrained: false
  num_classes: 0
  metadata: true
  in_chans: 1
  dropout: 0.1

profile_encoder_args:
  dim_in: 6
  dim_out: 128
  num_head: 4
  num_layers: 6
  dim_feedforward: 1024
  dropout: 0.1
  activation: 'gelu'
  max_len: *max_len

coordination_args:
    method: 'clip'  # distance, clip, or rank
    #'margin': 5

optim_args:
  lr: 5.0e-3
  momentum: 0.9
  weight_decay: 1.0e-3
  nesterov: true

trainer_args:
  precision: '16-mixed'
  min_epochs: 40
  max_epochs: 200
  accumulate_grad_batches: 4
  val_check_interval:
  check_val_every_n_epoch: 1


